apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todoapp
data:
  PYTHONUNBUFFERED: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;ну 