apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  DB_USER: dXNlcg==
  DB_PASSWORD: cGFzc3dvcmQ=
stringData:
  DB_NAME: tododb
  DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
stringData:
  DB_NAME: tododb
